export const FETCH_EVENT_LIST_LOADING = 'FETCH_EVENT_LIST_LOADING';
export const FETCH_EVENT_LIST_SUCCESSFUL = 'FETCH_EVENT_LIST_SUCCESSFUL';
export const FETCH_EVENT_LIST_FAIL = 'FETCH_EVENT_LIST_FAIL';